#!/usr/bin/env ruby
# Pushes the worktree branch to origin and opens a PR via gh.
# Cleans up the worktree after push regardless of PR creation outcome.
#
# PR title format (mirrors dispatcher SKILL.md):
#   Fix AppSignal incident #<number> — <ExceptionName>
#
# PR body includes the incident ID so build-known-work can find this PR
# in future runs via the "AppSignal #<number>" pattern match.

require "json"

inputs         = JSON.parse($stdin.read)
worktree       = inputs["worktree_path"]
branch         = inputs["branch_name"]
repo           = inputs["repo"]
incident_number = inputs["incident_number"]
incident_id    = inputs["incident_id"]
exception_name = inputs["exception_name"]
diff_summary   = inputs["diff_summary"]

unless Dir.exist?(worktree.to_s)
  $stderr.puts "worktree not found: #{worktree}"
  exit 1
end

# Push branch.
push_out = `git -C #{worktree} push origin #{branch} 2>&1`
unless $?.success?
  $stderr.puts "git push failed: #{push_out}"
  exit 1
end

pr_title = "Fix AppSignal incident ##{incident_number} — #{exception_name}"
pr_body = <<~BODY
  Automated fix for AppSignal incident ##{incident_number}.

  **Exception:** #{exception_name}
  **Incident ID:** #{incident_id}

  #{diff_summary.to_s.strip}

  ---
  *Generated by agent-kitchen appsignal-incident-fix process.*
BODY

pr_out = `gh pr create \
  --repo #{repo} \
  --title #{pr_title.shellescape} \
  --body #{pr_body.shellescape} \
  --head #{branch} \
  --base main 2>&1`

unless $?.success?
  $stderr.puts "gh pr create failed: #{pr_out}"
  exit 1
end

pr_url    = pr_out.strip.lines.last.strip
pr_number = pr_url.split("/").last.to_i

# Clean up worktree after successful push.
`git worktree remove --force #{worktree} 2>/dev/null`

$stdout.puts JSON.dump({
  "pr_url"    => pr_url,
  "pr_number" => pr_number
})
